version: '3'

services:
    auth-server:
        build: ./auth_server/
        command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0:8000"
        restart: unless-stopped
        ports:
            - "8000:8000"
        volumes:
            - ./auth_server/:/code
        networks:
            - servers
    
    client:
        build: ./client/
        command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0:8001"
        restart: unless-stopped
        ports:
            - "8001:8001"
        volumes:
            - ./client/:/code
        networks:
            - servers
    
    resource-server:
        build: resource_server/
        command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0:8002"
        restart: unless-stopped
        ports:
            - "8002:8002"
        volumes:
            - ./resource_server/:/code
        networks:
            - servers

networks:
    servers:
