# Generated by Django 2.2.12 on 2020-05-20 17:24

import auth_server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration',
            field=models.DateTimeField(default=auth_server.models.getExpiration),
        ),
    ]
