# Generated by Django 3.0.6 on 2020-05-17 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_server', '0003_auto_20200517_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 20, 30, 26, 553132)),
        ),
    ]
