# Generated by Django 2.2.12 on 2020-05-17 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_server', '0004_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 19, 30, 41, 542851)),
        ),
    ]
